//
//  EvalSampleBrowser.swift
//  Wanderlust
//
//  Real generated output from the §13 evaluation matrix, rendered in the real
//  screen.
//

#if DEBUG
import CoreArchitecture
import CoreModels
import SwiftUI

/// One destination's actual model output, as generated by the evaluation run.
///
/// This is not mock data. Every string in `EvalSamples.json` came back from
/// `gpt-4o-mini` during the run recorded in
/// `ConvexBackend/eval/results/run-2026-08-05-2-link-fix.json`, under the split
/// variant the D15 measurement selected.
///
/// It exists because the one thing the evaluation matrix cannot score is
/// **factuality** — no offline check knows whether a restaurant exists, whether
/// a neighbourhood is really quiet, or whether the verdict on a landmark is the
/// one a local would give. That judgement needs a person, and a person reads
/// output far better in the layout it will actually appear in than as JSON.
/// Reading it here also catches the things JSON hides: a verdict that overflows
/// its card, a place name that renders without a link, prose that looked fine
/// in a diff and reads as filler on a phone.
struct EvalSample: Decodable, Identifiable {
    let id: String
    /// "Barcelona, Spain · couple · 3d · may"
    let label: String
    /// Which §13 destination archetype this row stands in for.
    let archetype: String
    /// What this fixture was chosen to catch. Read it before reading the output.
    let watchFor: String
    let destination: String
    let durationDays: Int
    let startMonth: String
    let groupType: String

    let itinerary: Trip.Itinerary
    let suggestions: Trip.Suggestions
    let interestPrompts: [String]
    let worthIt: [Trip.WorthItItem]
    let whereToStay: [Trip.StayArea]

    static let all: [EvalSample] = {
        guard let url = Bundle.main.url(forResource: "EvalSamples", withExtension: "json"),
              let data = try? Data(contentsOf: url),
              let samples = try? JSONDecoder().decode([EvalSample].self, from: data)
        else {
            assertionFailure("EvalSamples.json missing or no longer decodable")
            return []
        }
        return samples
    }()

    /// The screen state this sample renders as.
    ///
    /// `.savedTrip` with no `generationRequest`, so opening it calls nothing and
    /// costs nothing — the content is already here. Everything is `.loaded`,
    /// which is also what makes the Worth-it pill appear.
    var outputState: TripOutputStore.State {
        var state = TripOutputStore.State(
            details: Trip.Details(
                destination: Place(name: destination),
                members: Trip.Details.Members(
                    groupType: Trip.Details.GroupType(rawValue: groupType) ?? .solo
                ),
                duration: durationDays,
                month: Self.month(startMonth)
            ),
            saved: true,
            mode: .savedTrip
        )
        state.itineraryResponse = .loaded(itinerary)
        state.suggestionsResponse = .loaded(suggestions)
        state.worthItResponse = .loaded(worthIt)
        state.whereToStayResponse = .loaded(whereToStay)
        state.interestPrompts = interestPrompts
        return state
    }

    /// `Month`'s raw values are genuinely mixed case — `august` is spelled
    /// `August`, `september` is `September`, the rest are lowercase. A plain
    /// `Month(rawValue:)` therefore returns `nil` for two of the eight fixtures
    /// and would silently label them January.
    private static func month(_ raw: String) -> Month {
        Month.allCases.first { $0.rawValue.lowercased() == raw.lowercased() } ?? .january
    }
}

/// Picks a destination, then opens the real trip output screen on it.
struct EvalSampleBrowser: View {
    var body: some View {
        List {
            Section {
                Text("Real output from the evaluation run — not mock data. The matrix scores links, repetition, completeness and lane correctness on its own. What it cannot score is whether any of this is TRUE, which is what this list is for.")
                    .font(.footnote)
                    .foregroundStyle(.secondary)
            }

            ForEach(EvalSample.all) { sample in
                NavigationLink {
                    TripOutputScreen(initialState: sample.outputState)
                } label: {
                    VStack(alignment: .leading, spacing: 4) {
                        Text(sample.label)
                            .font(.system(size: 15, weight: .semibold))
                        Text(sample.archetype.replacingOccurrences(of: "-", with: " "))
                            .font(.caption)
                            .foregroundStyle(Color.appTint)
                        Text(sample.watchFor)
                            .font(.caption2)
                            .foregroundStyle(.secondary)
                            .fixedSize(horizontal: false, vertical: true)
                    }
                    .padding(.vertical, 2)
                }
            }
        }
        .navigationTitle("Eval output")
        .navigationBarTitleDisplayMode(.inline)
    }
}

#Preview {
    NavigationStack { EvalSampleBrowser() }
}
#endif
